//grunt-start
/// <reference path="domain/domain.d.ts" />
/// <reference path="domain/env/dev.ts" />
/// <reference path="domain/env/env.d.ts" />
/// <reference path="domain/lib/api/role.ts" />
/// <reference path="domain/lib/api/time.ts" />
/// <reference path="domain/lib/employee/employee.ts" />
/// <reference path="domain/lib/organization.ts" />
/// <reference path="domain/lib/organization/not-cqrs-organization.ts" />
/// <reference path="domain/lib/organization/organization.d.ts" />
/// <reference path="domain/lib/schedule/template/template-day.ts" />
/// <reference path="domain/lib/schedule/template/template-role.ts" />
/// <reference path="domain/lib/schedule/template/template-schedule.ts" />
/// <reference path="domain/lib/schedule/template/template-shift.ts" />
/// <reference path="domain/lib/schedule/template/template.d.ts" />
/// <reference path="domain/lib/schedule/work/word-day.ts" />
/// <reference path="domain/lib/schedule/work/work-role.ts" />
/// <reference path="domain/lib/schedule/work/work-schedule.ts" />
/// <reference path="domain/lib/schedule/work/work-shift.ts" />
/// <reference path="domain/lib/schedule/work/work.d.ts" />
/// <reference path="domain/server.ts" />
/// <reference path="models/work-schedule/typescript-test.ts" />
/// <reference path="msgbus.ts" />
/// <reference path="repos/organization/organization-mongoose-data-source.ts" />
/// <reference path="repos/organization/organization-repo.ts" />
/// <reference path="repos/typings/organization-repo.d.ts" />
/// <reference path="repos/typings/template-schedule-data.d.ts" />
/// <reference path="repos/typings/work-schedule-data.d.ts" />
/// <reference path="typings/tsd.d.ts" />
//grunt-end 
//# sourceMappingURL=references.js.map